chore: add tests to pre-push git script

diff --git a/.githooks/pre-push b/.githooks/pre-push
--- a/.githooks/pre-push
+++ b/.githooks/pre-push
@@ -20,6 +20,19 @@ if [ $? -ne 0 ] ; then
 fi
 
 echo ""
+echo -e "${YELLOW}Executing Tests ...${NOCOLOR}"
+echo ""
+
+dotnet test --verbosity minimal
+
+if [ $? -ne 0 ] ; then
+    echo ""
+	echo -e "${RED}One or more tests failed. Please fix the problems before pushing the changes${NOCOLOR}"
+	echo ""
+	exit 1
+fi
+
+echo ""
 echo -e "${GREEN}Everything is ok!${NOCOLOR}"
 echo ""
 
